### ISSUE TITLE
Only using CPU in Jupyter Notebook

### ISSUE THREAD

**Issue by nilsstre** [wildltr/ptranking#10]
Hi,

How do I set the library to only use CPU when I run it in Jupyter Notebook I can only found instructions for the [command line](https://wildltr.github.io/ptranking/how_to_start/Get_Started/)

**Comment by ii-research-yu** [comment]
@nilsstre I am sorry for the late reply. As shown in the testing code, by changing the setting of cuda as None.
{
cuda = None				# the gpu id, e.g., 0 or 1, otherwise, set it as None indicating to use cpu
}
