### ISSUE TITLE
Data_Eval_ScoringFunction.json File

### ISSUE THREAD

**Issue by CharlotteYang12345** [wildltr/ptranking#12]
Hello!

The JSON file on https://wildltr.github.io/ptranking/how_to_start/Configuration/ is not available. Would you pls share the JSON file?

Many thanks,
Charlotte

**Comment by ii-research-yu** [comment]
@CharlotteYang12345 hi, sorry for the inconvenience, please first refer to the source code folder: ptranking/testing/ltr_adhoc/json/
we will update it ASAP, thanks.
