### ISSUE TITLE
the listwise approach?

### ISSUE THREAD

**Issue by nijiazhi** [wildltr/ptranking#13]
Thanks for your excellent work~

Some papers say "lambdaRank" and "lambdaMart" are pairwise approach, because they come from the ranknet which is a pairwise method. In your paper, you put the two approaches into listwise.  What's your opinion?

**Comment by ii-research-yu** [comment]
@nijiazhi hi, thanks for the question. I'd like to view it as a listwise method, since listwise information has been used when computing the pairwise loss.
