### ISSUE TITLE
Write up reinforcement sequence ranking idea and link it to existing literature

### ISSUE THREAD

**Issue by GabrielPereyra** [wildltr/ptranking#15]
Represent song recommendation problem as a sequence learning (RL?) problem: have a dataset of sequences of song_id -> listen_time -> action(skip, like, dislike, search, etc) -> song_id -> listen_time... Want to train a model that can predict the next song_id in this sequence with respect to a user_id. Furthermore, we want to do this in a way that reduces the probability of a skip token (connection to RL?). How does spotify do song recommendation?

**Comment by ii-research-yu** [comment]
@GabrielPereyra I am afraid I can not help w.r.t. your questions.
